apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /orders/?(.*)
            pathType: Prefix
            backend:
              service:
                name: order-service-lb
                port:
                  number: 5000
          - path: /stock/?(.*)
            pathType: Prefix
            backend:
              service:
                name: stock-service-lb
                port:
                  number: 5000
          - path: /payment/?(.*)
            pathType: Prefix
            backend:
              service:
                name: payment-service-lb
                port:
                  number: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: order-service-lb
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: order-app
---
apiVersion: v1
kind: Service
metadata:
  name: stock-service-lb
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: stock-app
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service-lb
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: payment-app
