version: "3"
services:

  gateway:
    image: nginx:latest
    volumes:
      - ./gateway_nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"

  order-service:
    build:
      context: src
      dockerfile: order/Dockerfile
    command: ./order-gin
    image: order:latest
    environment:
      # - GIN_MODE=release
      - MACHINE_ID=1
      - PAYMENT_SERVICE_URL=http://gateway:80/payment/
      - STOCK_SERVICE_URL=http://gateway:80/stock/
    env_file:
      - env/order_redis.env

  order-db:
    image: redis:latest
    command: redis-server --requirepass redis --maxmemory 512mb

  stock-service:
    build:
      context: src
      dockerfile: stock/Dockerfile
    command: ./stock-gin
    image: stock:latest
    environment:
      # - GIN_MODE=release
      - MACHINE_ID=1
    env_file:
      - env/stock_redis.env

  stock-db:
    image: redis:latest
    command: redis-server --requirepass redis --maxmemory 512mb

  payment-service:
    build:
      context: src
      dockerfile: payment/Dockerfile
    command: ./payment-gin
    image: user:latest
    environment:
      # - GIN_MODE=release
      - MACHINE_ID=1
      - ORDER_SERVICE_URL=http://gateway:80/orders/
    env_file:
      - env/payment_redis.env

  payment-db:
    image: redis:latest
    command: redis-server --requirepass redis --maxmemory 512mb
