version: "3"
services:

  gateway:
    image: nginx:latest
    volumes:
      - ./gateway_nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"

  order-db:
    image: redis:latest
    command: redis-server --requirepass redis --maxmemory 512mb

  order-service:
    build:
      context: src
      dockerfile: order/Dockerfile
    command: ./order-gin
    image: order:latest
    environment:
      # - GIN_MODE=release
      - REDIS_ADDRS=order-db:6379
      - REDIS_PASSWORD=redis
      - REDIS_DB=0
      - PAYMENT_SERVICE_URL=http://gateway:80/payment/
      - STOCK_SERVICE_URL=http://gateway:80/stock/
      - MACHINE_ID=1/1
      - WDM_DEBUG=1

  stock-db:
    image: redis:latest
    command: redis-server --requirepass redis --maxmemory 512mb

  stock-service:
    build:
      context: src
      dockerfile: stock/Dockerfile
    command: ./stock-gin
    image: stock:latest
    environment:
      # - GIN_MODE=release
      - REDIS_ADDRS=stock-db:6379
      - REDIS_PASSWORD=redis
      - REDIS_DB=0
      - MACHINE_ID=1/1
      - WDM_DEBUG=1

  payment-db:
    image: redis:latest
    command: redis-server --requirepass redis --maxmemory 512mb

  payment-service:
    build:
      context: src
      dockerfile: payment/Dockerfile
    command: ./payment-gin
    image: user:latest
    environment:
      # - GIN_MODE=release
      - REDIS_ADDRS=payment-db:6379
      - REDIS_PASSWORD=redis
      - REDIS_DB=0
      - ORDER_SERVICE_URL=http://gateway:80/orders/
      - MACHINE_ID=1/1
      - WDM_DEBUG=1
