name: build docker images

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: build order and push to ghcr
        uses: docker/build-push-action@v4
        with:
          context: src
          file: src/order/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/order:latest

      - name: build payment and push to ghcr
        uses: docker/build-push-action@v4
        with:
          context: src
          file: src/payment/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/payment:latest

      - name: build stock and push to ghcr
        uses: docker/build-push-action@v4
        with:
          context: src
          file: src/stock/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/stock:latest
